# A script to automate changing the desktop theme
# Generates a color scheme using Themer and edits the color definitions in .Xresources

THEMER_DIR=$HOME/.config/themer
XRES=$HOME/.Xresources
THEME_PARSER=$HOME/scripts/env_theme/themer_xresources.py
BACKUP_DIR=$HOME/backups


if [ $1 == "generate" ]; then
    if [ -z $2 ]; then
        echo "Please specify a theme name"
        exit 1
    fi

    if [ -z $3 ]; then
        echo "Please specify a wallpaper file"
        exit 1
    fi
    #generate the theme
    themer $1 $2 $3

    # Create a temporary file because python can't find files without extensions
    touch $THEMER_DIR/$2/.Xresources.txt
    cp "$XRES" "$XRES-copy.txt"
    
    # Write new .Xresources file for given theme and save alongside files generated by themer
    python $THEME_PARSER $2
    mv $THEMER_DIR/$2/.Xresources.txt $THEMER_DIR/$2/.Xresources
    rm "$XRES-copy.txt"
fi

if [ $1 == "activate" ]; then
    # back up old .Xresources
    cp $XRES $BACKUP_DIR/Xresources

    # themer activate
    themer $1 $2

    # copy to ~/.Xresources, set wallpaper, and reload config files
    cp $THEMER_DIR/$2/.Xresources $XRES
    feh --bg-scale $THEMER_DIR/$2/wallpaper.jpg
    themer render
    xrdb $XRES
fi
