#! /bin/sh

sxhkd &

bspc monitor -d term dev web mail media doc chat misc

bspc config border_width         0
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Code desktop='^2'
bspc rule -a Sublime_text desktop='^2'
bspc rule -a QtCreator desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a Thunderbird desktop='^4'
bspc rule -a kontact desktop='^4'
bspc rule -a vlc desktop='^5'
bspc rule -a llpp desktop='^6'
bspc rule -a discord desktop='^7'
bspc rule -a origin.exe state=floating

$HOME/.config/polybar/launch.sh &
picom -b --experimental-backends
