#! /bin/sh

sxhkd &

bspc monitor -d term dev web mail media doc chat misc

bspc config border_width         8
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh &
betterlockscreen -u ~/media/pics/walls/3840x1600/227491.jpg
albert &

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
