#! /bin/sh

sxhkd &

bspc monitor DP-4 -d term dev web mail
bspc monitor HDMI-0 -d media doc chat misc
bspc monitor DP-4 -s HDMI-0

bspc config border_width         0
bspc config window_gap          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a code-oss desktop='^2'
bspc rule -a Sublime_text desktop='^2'
bspc rule -a QtCreator desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a Thunderbird desktop='^4'
bspc rule -a vlc desktop='^5'
bspc rule -a llpp desktop='^6'
bspc rule -a discord desktop='^7'

$HOME/.config/polybar/launch.sh &
picom -b
multilockscreen -u '/home/jalen/media/pics/walls/3064x1724/IqqbRKA.jpg' -r 2560x1440
albert &
